service:
  name: sfn-test

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  stage: ${opt:stage, self:provider.stage}

plugins:
  - serverless-step-functions
  - serverless-webpack

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs12.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  - ${file(./serverless/functions/myStateMachine.yml)}
  - ${file(./serverless/functions/mapStateMachine.yml)}

resources:
  Resources:
    mapStateMachineLogGroup: ${file(./serverless/logGroups/mapStateMachine.yml)}

stepFunctions:
  validate: true
  stateMachines:
    myStateMachine: ${file(./serverless/stateMachines/myStateMachine.yml)}
    mapStateMachine: ${file(./serverless/stateMachines/mapStateMachine.yml)}
