service:
  name: step-functions-test

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-step-functions
  - serverless-webpack

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: functions/hello.handler
  echo:
    handler: functions/echo.handler

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: myStateMachine
      tracingConfig:
        enabled: true
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: echo
          echo:
            Type: Task
            Resource:
              Fn::GetAtt: [echo, Arn]
            End: true
  validate: true
